<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-10T18:55:36 IST" name="Suite" finished-at="2022-08-10T18:55:48 IST" duration-ms="12009">
    <groups>
    </groups>
    <test started-at="2022-08-10T18:55:36 IST" name="Test" finished-at="2022-08-10T18:55:48 IST" duration-ms="12009">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:tests.LoginTest@4fb61f4a]" started-at="2022-08-10T18:55:25 IST" name="init" finished-at="2022-08-10T18:55:36 IST" duration-ms="10914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="initObject()[pri:0, instance:tests.LoginTest@4fb61f4a]" started-at="2022-08-10T18:55:36 IST" name="initObject" finished-at="2022-08-10T18:55:36 IST" duration-ms="55" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initObject -->
        <test-method signature="verifybuttontext()[pri:1, instance:tests.LoginTest@4fb61f4a]" started-at="2022-08-10T18:55:36 IST" name="verifybuttontext" finished-at="2022-08-10T18:55:36 IST" duration-ms="76" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifybuttontext -->
        <test-method signature="login()[pri:2, instance:tests.LoginTest@4fb61f4a]" started-at="2022-08-10T18:55:36 IST" name="login" finished-at="2022-08-10T18:55:42 IST" duration-ms="6405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@4fb61f4a]" started-at="2022-08-10T18:55:48 IST" name="tearDown" finished-at="2022-08-10T18:55:48 IST" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.HomeTest">
        <test-method is-config="true" signature="initObject()[pri:0, instance:tests.HomeTest@9f116cc]" started-at="2022-08-10T18:55:42 IST" name="initObject" finished-at="2022-08-10T18:55:42 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initObject -->
        <test-method signature="goToTab()[pri:1, instance:tests.HomeTest@9f116cc]" started-at="2022-08-10T18:55:42 IST" name="goToTab" finished-at="2022-08-10T18:55:46 IST" duration-ms="3541" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at tests.HomeTest.goToTab(HomeTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToTab -->
        <test-method signature="logout()[pri:2, instance:tests.HomeTest@9f116cc]" started-at="2022-08-10T18:55:46 IST" name="logout" finished-at="2022-08-10T18:55:48 IST" duration-ms="1811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- tests.HomeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
